### ISSUE TITLE
Installation with npm fails (again)

### ISSUE THREAD

**Issue by dtillner** [ContaAzul/creditcard.js#170]
With version 3.0.30 installation with npm fails with error "yarn not found".

Probably this is because of this line in `package.json`

```json
"preinstall": "yarn dlx only-allow yarn",
```

Reintroduced problem from #159

**Comment by yuigoto** [comment]
Version `3.0.33` still failing when installing with `npm` with the `yarn not found error`.

It's possible to install if you're using `bun` as package manager.

**Comment by eigood** [comment]
This was done in a minor point release, but is a definite breaking change, and should have bumped to a more major version.

**Comment by dtillner** [comment]
No it should not have been committed at all. It makes absolutely no sense to limit this package to yarn. 

As @cirocfc already stated https://github.com/ContaAzul/creditcard.js/issues/159#issuecomment-1439076861 this was committed accidently from internal packages.

But it doesn't matter anyways because this repository seems to be dead.

**Comment by cirocfc** [comment]
Hey guys!

Sorry we've been absent. This project doesn't really need much attention inside the company as the code works perfectly inside our software. I get that it is used in many other projects and I try to help when I can. From what've seen and remember, the code shipped to npm has the hooks disabled. Are you guys still having problems?

https://www.npmjs.com/package/creditcard.js?activeTab=code

<img width="806" height="643" alt="Image" src="https://github.com/user-attachments/assets/58400dfd-22ca-43a2-b541-10388ffe01ce" />

**Comment by eigood** [comment]
Yes, still having problems.  I don't think those underscores do what you think they do.

<pre>
npm install --verbose creditcard.js@3.0.34
...
npm info run creditcard.js@3.0.34 preinstall node_modules/creditcard.js yarn dlx only-allow yarn
...
npm info run creditcard.js@3.0.34 preinstall { code: 1, signal: null }
npm verbose stack Error: command failed
npm verbose stack     at promiseSpawn (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
npm verbose stack     at spawnWithShell (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:124:10)
npm verbose stack     at promiseSpawn (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
npm verbose stack     at runScriptPkg (/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:77:13)
npm verbose stack     at runScript (/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:12)
npm verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/rebuild.js:329:17
npm verbose stack     at run (/usr/local/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:67:22)
npm verbose stack     at /usr/local/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:84:9
npm verbose stack     at new Promise (<anonymous>)
npm verbose stack     at callLimit (/usr/local/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:35:69)
npm verbose pkgid creditcard.js@3.0.34
npm error code 1
npm error path /srv/app/node_modules/creditcard.js
npm error command failed
npm error command sh -c yarn dlx only-allow yarn
npm error error This project's package.json defines "packageManager": "yarn@3.4.1". However the current global version of Yarn is 1.22.22.
npm error
npm error Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
npm error Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.
npm verbose cwd /srv/app
npm verbose os Linux 6.1.0-15-amd64
npm verbose node v22.9.0
npm verbose npm  v10.8.3
</pre>
